USE [master]
GO

IF NOT EXISTS(SELECT * FROM sys.databases WHERE name = 'SQLAdmin')

BEGIN

/****** Object:  Database [SQLAdmin]    Script Date: 15/07/2025 13:59:47 ******/
	CREATE DATABASE [SQLAdmin]
	 CONTAINMENT = NONE
	 ON  PRIMARY 
	( NAME = N'SQLAdmin', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\SQLAdmin.mdf' , SIZE = 204800KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
	 LOG ON 
	( NAME = N'SQLAdmin_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\SQLAdmin_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
	 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF


END
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SQLAdmin].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SQLAdmin] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SQLAdmin] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SQLAdmin] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SQLAdmin] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SQLAdmin] SET ARITHABORT OFF 
GO

ALTER DATABASE [SQLAdmin] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SQLAdmin] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SQLAdmin] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SQLAdmin] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SQLAdmin] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SQLAdmin] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SQLAdmin] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SQLAdmin] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SQLAdmin] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SQLAdmin] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SQLAdmin] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SQLAdmin] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SQLAdmin] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SQLAdmin] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SQLAdmin] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SQLAdmin] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SQLAdmin] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SQLAdmin] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SQLAdmin] SET  MULTI_USER 
GO

ALTER DATABASE [SQLAdmin] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SQLAdmin] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SQLAdmin] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SQLAdmin] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SQLAdmin] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SQLAdmin] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SQLAdmin] SET QUERY_STORE = ON
GO

ALTER DATABASE [SQLAdmin] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [SQLAdmin] SET  READ_WRITE 
GO


